version: '3'
services:
  db:
    image: library/mysql:5.6.22
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=ERROR_FOR_DIVISION_BY_ZERO --sql-mode=ERROR_FOR_DIVISION_BY_ZERO"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    image: ayumi
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
    environment: 
      SERVERNAME: "db"